# Generated by Django 4.1.6 on 2023-02-04 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['name']},
        ),
    ]
